#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true

# Move floating windows with mouse
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# WAL COLOURS
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a mplayer2 state=floating
bspc rule -a discord state=floating desktop='^10' rectangle=800x800
bspc rule -a Alacritty state=floating
bspc rule -a Thunar state=floating
bspc rule -a FileZilla state=floating
bspc rule -a Transmission-gtk state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Steam state=floating
bspc rule -a Termius state=floating

bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a VSCodium desktop = '^1'

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating

bspc rule -a "*:*:Picture in picture" state=floating rectangle=427x240+1478+825
bspc rule -a "*:*:Picture-in-picture" state=floating rectangle=427x240+1478+825
bspc rule -a "*:*:Android Studio Setup Wizard" state=floating
bspc rule -a "*:*:Welcome to Android Studio" state=floating

picom --experimental-backends &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
